### ISSUE TITLE
website watching fixes

### ISSUE THREAD

**Issue by schmir-at-bb** [trustlines-protocol/watch#16]
- [x] add bs4 to setup.py
- [x] make --url a required argument
- [x] report the service name without user/password when url is specified as https://username:password@example.com/auction.html
- [x] report the local hostname doing the requests as host field (so, we could run this from multiple machines)
- [x] handle HTTP errors in a sensible way: At the moment these are ignored, e,g,  `tl-watch get-website-hash --url https://test.trustlines.auction` prints a hash even though the website is password protected
- [x] log which pages are being fetched

**Comment by schmir-at-bb** [comment]
maybe I should have mentioned that the logs should not be invisible:
```
/trustlines/protocol/watch (git)-[master] % tl-watch get-website-hash --url https://github.com
29c5d8cfe24b3024940edbf55a7921216611e0b643cbaa0aaca7d6d13b211dbd
```

**Comment by schmir-at-bb** [comment]
Though I can see them when watching a website.

**Comment by weilbith** [comment]
Hmm which level is enabled per default and which do you set where it is running? :thinking:

**Comment by schmir-at-bb** [comment]
Please have a look at the code.
